apiVersion: v1
kind: Pod
metadata:
  name: anjasmara_service_general
spec:
  containers:
  - name: kubectl
    image: joshendriks/alpine-k8s
    command:
    - /bin/cat
    tty: true    
  - name: anjasmara_service_general
    image: mulki12/anjasmara_service_general
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
      - name: anjasmara_service_general-secret
        mountPath: /anjasmara_service_general/.docker
  volumes:
    - name: anjasmara_service_general-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
