
   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anjasmara-service-general-deployment
  labels:
    app: anjasmara-service-general
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anjasmara-service-general
  template:
    metadata:
      labels:
        app: anjasmara-service-general 
    spec:
      containers:
      - name: anjasmara-service-general
        image: CONTAINER_IMAGE221047265242.dkr.ecr.ap-southeast-1.amazonaws.com/app_and_version
        resources:
          requests:
          memory: "128Mi"
          cpu: "500m"
          limits:
          memory: "256Mi"
          cpu: "1000m"
        ports:
        - containerPort: 3001
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: anjasmara-service-general
spec:
  selector:
    app: anjasmara-service-general 
  type: NodePort
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
    nodePort: 31111
