name: general-ci

on:
  push:
    branches: [ master ]
]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/docker/anjasmara_service_general/composer/cache/files
        key: dependencies-composer-${{ hashFiles('composer.json') }}
    - name: Setup PHP
      uses: shivammathur/setup-php@v2       with:
        php-version: 7.44
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mcrypt, amqp
        coverage: none
    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-interaction --no-suggest
    - name: Install NPM dependencies
      run: npm install
    - name: Compile assets
      run: npm run production
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: anjasmara_service_general
      run: vendor/bin/phpunit --verbose

