name: general-ci-cd

on:
  push:
    branches: [ master ]

jobs:
  build-js:
    name: Build Js/Css
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Yarn Build
        run: |
          yarn install
      - name: Upload build files
        uses: actions/upload-artifact@v1
        with:
          name: assets
          path: public
  test-php:
    name: Test/Lint PHP
    runs-on: ubuntu-latest
    needs: build-js
    steps:
      - uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.4 # Use your PHP version
          extension-csv: mbstring, bcmath, pdo, pdo_mysql, sockets, amqp # Setup any required extensions for tests
      - name: Composer install
        run: composer install1
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: anjasmara_service_general
        run: vendor/bin/phpunit --verbose
      - name: composer migrate
        run: php artisan migrate:fresh
      
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [build-js, test-php]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
      - name: Download build assets
        uses: actions/download-artifact@v1
        with:
          name: assets
          path: public
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.4
          extension-csv: mbstring, bcmath, pdo, pdo_mysql, sockets, amqp
      - name: Composer install
        run: composer install
      - name: Generate key
        run: php artisan key:generate
      - name: Run Tests
        run: ./vendor/bin/phpunit
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: anjasmara_service_general
        run: vendor/bin/phpunit --verbose
      - name: composer migrate
        run: php artisan migrate:fresh
      - uses: actions/checkout@v2
      - name: Check Out Repo 
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/anjasmara_service_general:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

